// 初一上学期 · chuyi-shang · 200 词
// 数据来源:data/junior.json(grade === "chuyi-shang")
// 完整字段:id 在 generate-junior.js 里自动续号
module.exports = [
{"word":"i","phonetic":"/aɪ/","pos":"pron.","translation":"我","definition":"referring to oneself","root":"","family":["me","my","mine"],"examples":["I am a student.","I like apples.","I live in China."],"collocations":["I think","I want","I have"],"synonyms":["me","myself"],"antonyms":["you","they"],"keyword":"爱(谐音)+ 我爱我","image":"🙋","topic":"daily-life","grade":"chuyi-shang","frequency":5000,"difficulty":1}
,
{"word":"you","phonetic":"/juː/","pos":"pron.","translation":"你;你们","definition":"referring to the person addressed","root":"","family":["your","yours"],"examples":["You are my friend.","Are you happy?","You have a nice bag."],"collocations":["you and me","thank you","how are you"],"synonyms":[],"antonyms":["me","I"],"keyword":"U形似你","image":"👉","topic":"daily-life","grade":"chuyi-shang","frequency":4990,"difficulty":1}
,
{"word":"he","phonetic":"/hiː/","pos":"pron.","translation":"他","definition":"referring to a male person","root":"","family":["his","him"],"examples":["He is my brother.","He likes music.","He runs fast."],"collocations":["he and she","he said"],"synonyms":["him"],"antonyms":["she"],"keyword":"He=他(谐音)","image":"👨","topic":"family","grade":"chuyi-shang","frequency":4980,"difficulty":1}
,
{"word":"she","phonetic":"/ʃiː/","pos":"pron.","translation":"她","definition":"referring to a female person","root":"","family":["her","hers"],"examples":["She is tall.","She dances well.","She loves cats."],"collocations":["she said","she and he"],"synonyms":["her"],"antonyms":["he"],"keyword":"She=谁(谐音)","image":"👩","topic":"family","grade":"chuyi-shang","frequency":4970,"difficulty":1}
,
{"word":"it","phonetic":"/ɪt/","pos":"pron.","translation":"它","definition":"referring to a thing or animal","root":"","family":["its"],"examples":["It is a book.","It is raining.","It looks small."],"collocations":["it is","it seems"],"synonyms":["this","that"],"antonyms":[],"keyword":"It=伊特(谐音)","image":"📦","topic":"daily-life","grade":"chuyi-shang","frequency":4960,"difficulty":1}
,
{"word":"we","phonetic":"/wiː/","pos":"pron.","translation":"我们","definition":"referring to a group including oneself","root":"","family":["us","our","ours"],"examples":["We are classmates.","We love sports.","We live here."],"collocations":["we all","we should"],"synonyms":["us"],"antonyms":["they"],"keyword":"We=我们(谐音)","image":"👥","topic":"school","grade":"chuyi-shang","frequency":4950,"difficulty":1}
,
{"word":"they","phonetic":"/ðeɪ/","pos":"pron.","translation":"他们;她们;它们","definition":"referring to people or things already mentioned","root":"","family":["them","their","theirs"],"examples":["They are happy.","They went home.","They play football."],"collocations":["they all","they have"],"synonyms":["them"],"antonyms":["we"],"keyword":"They=贼(谐音)","image":"👨‍👩‍👧","topic":"daily-life","grade":"chuyi-shang","frequency":4940,"difficulty":1}
,
{"word":"my","phonetic":"/maɪ/","pos":"pron.","translation":"我的","definition":"belonging to me","root":"","family":["I","me","mine"],"examples":["My name is Tom.","This is my book.","My bag is blue."],"collocations":["my family","my friend","my school"],"synonyms":[],"antonyms":["your","his"],"keyword":"My=麦(谐音)","image":"👤","topic":"family","grade":"chuyi-shang","frequency":4930,"difficulty":1}
,
{"word":"your","phonetic":"/jɔːr/","pos":"pron.","translation":"你的;你们的","definition":"belonging to you","root":"","family":["you","yours"],"examples":["Your bag is nice.","Is this your pen?","Your name is Anna."],"collocations":["your name","your family"],"synonyms":[],"antonyms":["my","our"],"keyword":"Your=哟(谐音)","image":"👉","topic":"daily-life","grade":"chuyi-shang","frequency":4920,"difficulty":1}
,
{"word":"his","phonetic":"/hɪz/","pos":"pron.","translation":"他的","definition":"belonging to him","root":"","family":["he","him"],"examples":["His book is new.","This is his desk.","His sister is kind."],"collocations":["his name","his family"],"synonyms":[],"antonyms":["her","my"],"keyword":"His=黑子(谐音)","image":"👨","topic":"family","grade":"chuyi-shang","frequency":4910,"difficulty":1}
,
{"word":"her","phonetic":"/hɜːr/","pos":"pron.","translation":"她的","definition":"belonging to her","root":"","family":["she","hers"],"examples":["Her hair is long.","Her mother is a teacher.","That is her bag."],"collocations":["her name","her family"],"synonyms":[],"antonyms":["his","my"],"keyword":"Her=呵(谐音)","image":"👩","topic":"family","grade":"chuyi-shang","frequency":4900,"difficulty":1}
,
{"word":"am","phonetic":"/æm/","pos":"v.","translation":"是","definition":"first person singular of be","root":"","family":["be","is","are","was","were"],"examples":["I am a student.","I am happy.","I am ten years old."],"collocations":["I am","am not"],"synonyms":["be"],"antonyms":[],"keyword":"AM=俺(谐音)","image":"✅","topic":"daily-life","grade":"chuyi-shang","frequency":4890,"difficulty":1}
,
{"word":"is","phonetic":"/ɪz/","pos":"v.","translation":"是","definition":"third person singular of be","root":"","family":["be","am","are"],"examples":["He is tall.","It is a cat.","She is my friend."],"collocations":"is not","synonyms":["be"],"antonyms":[],"keyword":"Is=伊子(谐音)","image":"✅","topic":"daily-life","grade":"chuyi-shang","frequency":4880,"difficulty":1}
,
{"word":"are","phonetic":"/ɑːr/","pos":"v.","translation":"是","definition":"present plural of be","root":"","family":["be","am","is"],"examples":["We are friends.","You are clever.","They are happy."],"collocations":["are not","are you"],"synonyms":["be"],"antonyms":[],"keyword":"Are=啊(谐音)","image":"✅","topic":"daily-life","grade":"chuyi-shang","frequency":4870,"difficulty":1}
,
{"word":"be","phonetic":"/biː/","pos":"v.","translation":"是;存在","definition":"to exist; equal sign","root":"","family":["am","is","are","was","were","being","been"],"examples":["Be quiet, please.","I want to be a doctor.","Be happy."],"collocations":["be good","be kind","be there"],"synonyms":["exist"],"antonyms":[],"keyword":"Be=比(谐音)","image":"🌀","topic":"daily-life","grade":"chuyi-shang","frequency":4860,"difficulty":1}
,
{"word":"have","phonetic":"/hæv/","pos":"v.","translation":"有;拥有","definition":"to possess or own","root":"","family":["has","had","having"],"examples":["I have a cat.","Do you have a pen?","They have a big house."],"collocations":["have a look","have breakfast","have fun"],"synonyms":["own","possess"],"antonyms":["lack","lose"],"keyword":"Have=哈佛(谐音)","image":"🎁","topic":"daily-life","grade":"chuyi-shang","frequency":4850,"difficulty":1}
,
{"word":"has","phonetic":"/hæz/","pos":"v.","translation":"有","definition":"third person singular of have","root":"","family":["have","had"],"examples":["He has a bike.","She has two sisters.","Tom has a dog."],"collocations":["has to","has got"],"synonyms":["owns","possesses"],"antonyms":[],"keyword":"Has=哈子(谐音)","image":"🎁","topic":"daily-life","grade":"chuyi-shang","frequency":4840,"difficulty":1}
,
{"word":"do","phonetic":"/duː/","pos":"v.","translation":"做;干","definition":"to perform an action","root":"","family":["does","did","done","doing"],"examples":["I do my homework.","Do you like it?","They do well in math."],"collocations":["do homework","do sports","do well"],"synonyms":["perform","act"],"antonyms":[],"keyword":"Do=渡(谐音)","image":"⚙️","topic":"daily-life","grade":"chuyi-shang","frequency":4830,"difficulty":1}
,
{"word":"does","phonetic":"/dʌz/","pos":"v.","translation":"做","definition":"third person singular of do","root":"","family":["do","did"],"examples":["He does his best.","Does she sing?","It does work."],"collocations":["does not","does it"],"synonyms":[],"antonyms":[],"keyword":"Does=大子(谐音)","image":"⚙️","topic":"daily-life","grade":"chuyi-shang","frequency":4820,"difficulty":1}
,
{"word":"go","phonetic":"/ɡəʊ/","pos":"v.","translation":"去;走","definition":"to move from one place to another","root":"","family":["goes","went","gone","going"],"examples":["Let's go home.","I go to school by bus.","They go to the park."],"collocations":["go home","go to school","go shopping"],"synonyms":["move","travel"],"antonyms":["come","stay"],"keyword":"Go=勾(谐音)","image":"🚶","topic":"travel","grade":"chuyi-shang","frequency":4810,"difficulty":1}
,
{"word":"goes","phonetic":"/ɡəʊz/","pos":"v.","translation":"去","definition":"third person singular of go","root":"","family":["go","went","gone"],"examples":["He goes to work.","She goes home early.","Tom goes swimming."],"collocations":["goes well","goes to"],"synonyms":[],"antonyms":["comes"],"keyword":"Goes=勾子(谐音)","image":"🚶","topic":"daily-life","grade":"chuyi-shang","frequency":4800,"difficulty":1}
,
{"word":"come","phonetic":"/kʌm/","pos":"v.","translation":"来","definition":"to move toward the speaker","root":"","family":["comes","came","coming"],"examples":["Come here, please.","Come and see me.","They come from Beijing."],"collocations":["come here","come on","come back"],"synonyms":["arrive","approach"],"antonyms":["go","leave"],"keyword":"Come=卡姆(谐音)","image":"🏃","topic":"daily-life","grade":"chuyi-shang","frequency":4790,"difficulty":1}
,
{"word":"see","phonetic":"/siː/","pos":"v.","translation":"看见;明白","definition":"to perceive with eyes","root":"","family":["sees","saw","seen","seeing"],"examples":["I see a bird.","Can you see the moon?","Let's see."],"collocations":["see you","I see","see off"],"synonyms":["watch","look","observe"],"antonyms":["miss"],"keyword":"See=细(谐音)","image":"👀","topic":"daily-life","grade":"chuyi-shang","frequency":4780,"difficulty":1}
,
{"word":"look","phonetic":"/lʊk/","pos":"v.","translation":"看;看起来","definition":"to direct eyes at something","root":"","family":["looks","looked","looking"],"examples":["Look at me.","It looks beautiful.","He looks tired."],"collocations":["look at","look for","look like"],"synonyms":["see","watch","gaze"],"antonyms":[],"keyword":"Look=鲁克(谐音)","image":"👀","topic":"daily-life","grade":"chuyi-shang","frequency":4770,"difficulty":1}
,
{"word":"like","phonetic":"/laɪk/","pos":"v.","translation":"喜欢","definition":"to find pleasant or enjoyable","root":"","family":["likes","liked","liking"],"examples":["I like music.","Do you like apples?","She likes reading."],"collocations":["like this","I like","would like"],"synonyms":["love","enjoy"],"antonyms":["dislike","hate"],"keyword":"Like=莱克(谐音)","image":"❤️","topic":"emotions","grade":"chuyi-shang","frequency":4760,"difficulty":1}
,
{"word":"want","phonetic":"/wɒnt/","pos":"v.","translation":"想要","definition":"to desire or wish for","root":"","family":["wants","wanted","wanting"],"examples":["I want some water.","Do you want to go?","She wants a new dress."],"collocations":["want to","want some","I want"],"synonyms":["desire","wish"],"antonyms":["dislike"],"keyword":"Want=望特(谐音)","image":"🙏","topic":"daily-life","grade":"chuyi-shang","frequency":4750,"difficulty":1}
,
{"word":"get","phonetic":"/ɡet/","pos":"v.","translation":"得到;到达","definition":"to receive or obtain","root":"","family":["gets","got","gotten","getting"],"examples":["I get up early.","Get me a glass of water.","Did you get the news?"],"collocations":["get up","get home","get ready"],"synonyms":["obtain","receive"],"antonyms":["lose","give"],"keyword":"Get=盖特(谐音)","image":"🎯","topic":"daily-life","grade":"chuyi-shang","frequency":4740,"difficulty":1}
,
{"word":"make","phonetic":"/meɪk/","pos":"v.","translation":"制作;使","definition":"to create or produce","root":"","family":["makes","made","making"],"examples":["I make a cake.","Make the bed.","She makes me happy."],"collocations":["make friends","make a cake","make sure"],"synonyms":["create","produce"],"antonyms":["destroy","break"],"keyword":"Make=美克(谐音)","image":"🛠️","topic":"daily-life","grade":"chuyi-shang","frequency":4730,"difficulty":1}
,
{"word":"play","phonetic":"/pleɪ/","pos":"v.","translation":"玩;演奏","definition":"to engage in activity for enjoyment","root":"","family":["plays","played","playing"],"examples":["I play football.","Let's play games.","She plays the piano."],"collocations":["play with","play games","play sports"],"synonyms":["enjoy","perform"],"antonyms":["work"],"keyword":"Play=普雷(谐音)","image":"⚽","topic":"sports","grade":"chuyi-shang","frequency":4720,"difficulty":1}
,
{"word":"eat","phonetic":"/iːt/","pos":"v.","translation":"吃","definition":"to put food into mouth and chew","root":"","family":["eats","ate","eaten","eating"],"examples":["I eat breakfast at 7.","Do you eat meat?","We eat together."],"collocations":["eat breakfast","eat dinner","eat out"],"synonyms":["consume","dine"],"antonyms":["fast"],"keyword":"Eat=伊特(谐音)","image":"🍽️","topic":"food","grade":"chuyi-shang","frequency":4710,"difficulty":1}
,
{"word":"drink","phonetic":"/drɪŋk/","pos":"v.","translation":"喝","definition":"to take liquid into mouth","root":"","family":["drinks","drank","drunk","drinking"],"examples":["I drink water.","She drinks milk.","Do you drink coffee?"],"collocations":["drink water","drink tea","drink milk"],"synonyms":["sip","gulp"],"antonyms":[],"keyword":"Drink=准克(谐音)","image":"🥤","topic":"food","grade":"chuyi-shang","frequency":4700,"difficulty":1}
,
{"word":"read","phonetic":"/riːd/","pos":"v.","translation":"读;阅读","definition":"to look at and understand written words","root":"","family":["reads","reading"],"examples":["I read books.","She reads every night.","Read aloud, please."],"collocations":["read books","read aloud","read a story"],"synonyms":["study","scan"],"antonyms":[],"keyword":"Read=瑞德(谐音)","image":"📖","topic":"school","grade":"chuyi-shang","frequency":4690,"difficulty":1}
,
{"word":"write","phonetic":"/raɪt/","pos":"v.","translation":"写","definition":"to form letters on a surface","root":"","family":["writes","wrote","written","writing"],"examples":["I write a letter.","Write your name here.","She writes poems."],"collocations":["write down","write a letter","write a story"],"synonyms":["note","record"],"antonyms":["read","erase"],"keyword":"Write=瑞特(谐音)","image":"✏️","topic":"school","grade":"chuyi-shang","frequency":4680,"difficulty":1}
,
{"word":"run","phonetic":"/rʌn/","pos":"v.","translation":"跑","definition":"to move faster than walking","root":"","family":["runs","ran","running"],"examples":["I run every morning.","He runs very fast.","The dog runs in the park."],"collocations":["run fast","run away","run out of"],"synonyms":["jog","sprint","race"],"antonyms":["walk","stop"],"keyword":"Run=润(谐音)","image":"🏃","topic":"sports","grade":"chuyi-shang","frequency":4670,"difficulty":1}
,
{"word":"walk","phonetic":"/wɔːk/","pos":"v.","translation":"走;步行","definition":"to move at a regular pace","root":"","family":["walks","walked","walking"],"examples":["I walk to school.","We walk in the park.","She walks slowly."],"collocations":["walk to","walk home","walk around"],"synonyms":["stroll","stride"],"antonyms":["run"],"keyword":"Walk=沃克(谐音)","image":"🚶","topic":"daily-life","grade":"chuyi-shang","frequency":4660,"difficulty":1}
,
{"word":"talk","phonetic":"/tɔːk/","pos":"v.","translation":"说话;谈话","definition":"to speak in order to convey information","root":"","family":["talks","talked","talking"],"examples":["I talk with my friend.","Don't talk in class.","They talk about music."],"collocations":["talk to","talk about","talk with"],"synonyms":["speak","chat"],"antonyms":["listen","be quiet"],"keyword":"Talk=托克(谐音)","image":"💬","topic":"daily-life","grade":"chuyi-shang","frequency":4650,"difficulty":1}
,
{"word":"say","phonetic":"/seɪ/","pos":"v.","translation":"说","definition":"to utter words","root":"","family":["says","said","saying"],"examples":["He says hello.","Please say it again.","What did you say?"],"collocations":["say hello","say goodbye","I say"],"synonyms":["tell","speak","utter"],"antonyms":[],"keyword":"Say=塞(谐音)","image":"🗣️","topic":"daily-life","grade":"chuyi-shang","frequency":4640,"difficulty":1}
,
{"word":"tell","phonetic":"/tel/","pos":"v.","translation":"告诉;讲述","definition":"to communicate information","root":"","family":["tells","told","telling"],"examples":["Tell me a story.","I tell him the truth.","She tells jokes."],"collocations":["tell a story","tell me","tell about"],"synonyms":["inform","say"],"antonyms":[],"keyword":"Tell=特欧(谐音)","image":"📢","topic":"daily-life","grade":"chuyi-shang","frequency":4630,"difficulty":1}
,
{"word":"know","phonetic":"/nəʊ/","pos":"v.","translation":"知道;了解","definition":"to be aware of","root":"","family":["knows","knew","known","knowing"],"examples":["I know the answer.","Do you know her?","He knows a lot."],"collocations":["know about","know how","I know"],"synonyms":["understand","realize"],"antonyms":["ignore"],"keyword":"Know=挪(谐音)","image":"🧠","topic":"daily-life","grade":"chuyi-shang","frequency":4620,"difficulty":1}
,
{"word":"think","phonetic":"/θɪŋk/","pos":"v.","translation":"想;思考","definition":"to have a thought","root":"","family":["thinks","thought","thinking"],"examples":["I think so.","Think about it.","What do you think?"],"collocations":["I think","think about","think of"],"synonyms":["believe","consider"],"antonyms":[],"keyword":"Think=醒克(谐音)","image":"💭","topic":"daily-life","grade":"chuyi-shang","frequency":4610,"difficulty":1}
,
{"word":"take","phonetic":"/teɪk/","pos":"v.","translation":"拿;带走","definition":"to grab or carry","root":"","family":["takes","took","taken","taking"],"examples":["Take this book.","Take a photo.","I'll take the bus."],"collocations":["take a photo","take a look","take part"],"synonyms":["grab","seize"],"antonyms":["give","drop"],"keyword":"Take=特克(谐音)","image":"✋","topic":"daily-life","grade":"chuyi-shang","frequency":4600,"difficulty":1}
,
{"word":"give","phonetic":"/ɡɪv/","pos":"v.","translation":"给;给予","definition":"to hand over","root":"","family":["gives","gave","given","giving"],"examples":["Give me a hand.","I give him a gift.","Please give it back."],"collocations":["give a hand","give up","give back"],"synonyms":["offer","present","donate"],"antonyms":["take","receive"],"keyword":"Give=给夫(谐音)","image":"🎁","topic":"daily-life","grade":"chuyi-shang","frequency":4590,"difficulty":1}
,
{"word":"work","phonetic":"/wɜːrk/","pos":"v.","translation":"工作;学习","definition":"to engage in activity to earn money","root":"","family":["works","worked","working"],"examples":["I work hard.","My mother works in a hospital.","The machine works well."],"collocations":["work hard","work out","work with"],"synonyms":["labor","function"],"antonyms":["rest","play"],"keyword":"Work=沃克(谐音)","image":"💼","topic":"jobs","grade":"chuyi-shang","frequency":4580,"difficulty":1}
,
{"word":"study","phonetic":"/ˈstʌdi/","pos":"v.","translation":"学习;研究","definition":"to learn about a subject","root":"","family":["studies","studied","studying"],"examples":["I study English.","He studies math.","Study hard for the test."],"collocations":["study hard","study English","study for"],"synonyms":["learn","review"],"antonyms":[],"keyword":"Study=死打滴(谐音)","image":"📚","topic":"school","grade":"chuyi-shang","frequency":4570,"difficulty":1}
,
{"word":"learn","phonetic":"/lɜːrn/","pos":"v.","translation":"学习;学会","definition":"to gain knowledge","root":"","family":["learns","learned","learning"],"examples":["I learn English.","She learns fast.","Learn from mistakes."],"collocations":["learn about","learn from","learn to"],"synonyms":["study","master"],"antonyms":["teach","forget"],"keyword":"Learn=乐恩(谐音)","image":"📚","topic":"school","grade":"chuyi-shang","frequency":4560,"difficulty":1}
,
{"word":"teach","phonetic":"/tiːtʃ/","pos":"v.","translation":"教;教书","definition":"to give knowledge","root":"","family":["teaches","taught","teaching"],"examples":["I teach English.","She teaches kids.","He teaches us math."],"collocations":["teach English","teach oneself","teach kids"],"synonyms":["educate","instruct"],"antonyms":["learn","forget"],"keyword":"Teach=踢去(谐音)","image":"👩‍🏫","topic":"school","grade":"chuyi-shang","frequency":4550,"difficulty":1}
,
{"word":"help","phonetic":"/help/","pos":"v.","translation":"帮助","definition":"to assist","root":"","family":["helps","helped","helping"],"examples":["Help me, please.","Can you help me?","She helps her mother."],"collocations":["help with","help out","help me"],"synonyms":["assist","aid"],"antonyms":["hinder","ignore"],"keyword":"Help=哈佛(谐音)","image":"🤝","topic":"daily-life","grade":"chuyi-shang","frequency":4540,"difficulty":1}
,
{"word":"open","phonetic":"/ˈəʊpən/","pos":"v.","translation":"打开","definition":"to make something not closed","root":"","family":["opens","opened","opening"],"examples":["Open the door.","Open your book.","The shop opens at 9."],"collocations":["open the door","open up","open the window"],"synonyms":["unlock","unfold"],"antonyms":["close","shut"],"keyword":"Open=欧喷(谐音)","image":"📖","topic":"daily-life","grade":"chuyi-shang","frequency":4530,"difficulty":1}
,
{"word":"close","phonetic":"/kləʊz/","pos":"v.","translation":"关闭","definition":"to shut","root":"claud(关闭)","family":["closes","closed","closing"],"examples":["Close the window.","The store closes at 9.","Please close the door."],"collocations":["close to","close the door","close down"],"synonyms":["shut","seal"],"antonyms":["open"],"keyword":"Close=克罗斯(谐音)","image":"🚪","topic":"daily-life","grade":"chuyi-shang","frequency":4520,"difficulty":1}
,
{"word":"sit","phonetic":"/sɪt/","pos":"v.","translation":"坐","definition":"to be in a seated position","root":"","family":["sits","sat","sitting"],"examples":["Sit down, please.","I sit on the chair.","They sit together."],"collocations":["sit down","sit on","sit up"],"synonyms":["seat"],"antonyms":["stand"],"keyword":"Sit=西特(谐音)","image":"🪑","topic":"daily-life","grade":"chuyi-shang","frequency":4510,"difficulty":1}
,
{"word":"stand","phonetic":"/stænd/","pos":"v.","translation":"站;站立","definition":"to be upright on feet","root":"","family":["stands","stood","standing"],"examples":["Stand up, please.","He stands near the door.","Stand still."],"collocations":["stand up","stand by","stand for"],"synonyms":["rise"],"antonyms":["sit","lie"],"keyword":"Stand=死叹的(谐音)","image":"🧍","topic":"daily-life","grade":"chuyi-shang","frequency":4500,"difficulty":1}
,
{"word":"sleep","phonetic":"/sliːp/","pos":"v.","translation":"睡觉","definition":"to rest with eyes closed","root":"","family":["sleeps","slept","sleeping"],"examples":["I sleep at 10.","She sleeps early.","Don't sleep in class."],"collocations":["go to sleep","sleep well","sleep late"],"synonyms":["rest","doze"],"antonyms":["wake"],"keyword":"Sleep=死里扑(谐音)","image":"😴","topic":"daily-life","grade":"chuyi-shang","frequency":4490,"difficulty":1}
,
{"word":"wake","phonetic":"/weɪk/","pos":"v.","translation":"醒来;唤醒","definition":"to stop sleeping","root":"","family":["wakes","woke","woken","waking"],"examples":["I wake up at 7.","Wake up, Tom.","She wakes early."],"collocations":["wake up","wake sb up"],"synonyms":["awaken"],"antonyms":["sleep"],"keyword":"Wake=未克(谐音)","image":"⏰","topic":"daily-life","grade":"chuyi-shang","frequency":4480,"difficulty":1}
,
{"word":"wash","phonetic":"/wɒʃ/","pos":"v.","translation":"洗","definition":"to clean with water","root":"","family":["washes","washed","washing"],"examples":["Wash your hands.","I wash my face.","She washes the dishes."],"collocations":["wash hands","wash face","wash dishes"],"synonyms":["clean","rinse"],"antonyms":["dirty"],"keyword":"Wash=沃什(谐音)","image":"🚿","topic":"daily-life","grade":"chuyi-shang","frequency":4470,"difficulty":1}
,
{"word":"buy","phonetic":"/baɪ/","pos":"v.","translation":"买","definition":"to purchase","root":"","family":["buys","bought","buying"],"examples":["I buy a book.","She buys milk.","Buy me a gift."],"collocations":["buy something","buy a gift","buy for"],"synonyms":["purchase"],"antonyms":["sell"],"keyword":"Buy=败(谐音)","image":"🛒","topic":"daily-life","grade":"chuyi-shang","frequency":4460,"difficulty":1}
,
{"word":"sell","phonetic":"/sel/","pos":"v.","translation":"卖","definition":"to exchange for money","root":"","family":["sells","sold","selling"],"examples":["I sell books.","She sells flowers.","They sell fruit."],"collocations":["sell out","sell for","sell to"],"synonyms":["trade"],"antonyms":["buy","purchase"],"keyword":"Sell=塞欧(谐音)","image":"💰","topic":"daily-life","grade":"chuyi-shang","frequency":4450,"difficulty":1}
,
{"word":"put","phonetic":"/pʊt/","pos":"v.","translation":"放;放置","definition":"to place something somewhere","root":"","family":["puts","putting"],"examples":["Put it here.","Put on your coat.","I put the book on the desk."],"collocations":["put on","put up","put away"],"synonyms":["place","set"],"antonyms":["remove","take"],"keyword":"Put=普特(谐音)","image":"📍","topic":"daily-life","grade":"chuyi-shang","frequency":4440,"difficulty":1}
,
{"word":"find","phonetic":"/faɪnd/","pos":"v.","translation":"找到;发现","definition":"to discover","root":"","family":["finds","found","finding"],"examples":["I find my keys.","Find the answer.","She found a coin."],"collocations":["find out","find a way","find someone"],"synonyms":["discover","locate"],"antonyms":["lose"],"keyword":"Find=凡德的(谐音)","image":"🔍","topic":"daily-life","grade":"chuyi-shang","frequency":4430,"difficulty":1}
,
{"word":"use","phonetic":"/juːz/","pos":"v.","translation":"使用","definition":"to employ for a purpose","root":"","family":["uses","used","using"],"examples":["I use a pen.","Use your brain.","She uses a computer."],"collocations":["use up","used to","use for"],"synonyms":["employ","utilize"],"antonyms":[],"keyword":"Use=优子(谐音)","image":"🔧","topic":"daily-life","grade":"chuyi-shang","frequency":4420,"difficulty":1}
,
{"word":"live","phonetic":"/lɪv/","pos":"v.","translation":"居住;生活","definition":"to exist; to reside","root":"","family":["lives","lived","living"],"examples":["I live in Beijing.","They live happily.","Where do you live?"],"collocations":["live in","live on","live with"],"synonyms":["reside","dwell"],"antonyms":["die"],"keyword":"Live=力夫(谐音)","image":"🏠","topic":"places","grade":"chuyi-shang","frequency":4410,"difficulty":1}
,
{"word":"love","phonetic":"/lʌv/","pos":"v.","translation":"爱;喜爱","definition":"to feel deep affection","root":"","family":["loves","loved","loving"],"examples":["I love you.","She loves music.","We love our family."],"collocations":["love you","fall in love","love for"],"synonyms":["like","adore"],"antonyms":["hate"],"keyword":"Love=拉夫(谐音)","image":"❤️","topic":"emotions","grade":"chuyi-shang","frequency":4400,"difficulty":1}
,
{"word":"hate","phonetic":"/heɪt/","pos":"v.","translation":"讨厌;憎恨","definition":"to dislike intensely","root":"","family":["hates","hated","hating"],"examples":["I hate spiders.","She hates lies.","He hates cold weather."],"collocations":["hate to","hate for"],"synonyms":["detest","despise"],"antonyms":["love","like"],"keyword":"Hate=黑特(谐音)","image":"💔","topic":"emotions","grade":"chuyi-shang","frequency":4390,"difficulty":1}
,
{"word":"happy","phonetic":"/ˈhæpi/","pos":"adj.","translation":"快乐的;幸福的","definition":"feeling pleasure","root":"hap(运气)+-y","family":["happily","happiness","unhappy"],"examples":["I am happy.","She has a happy life.","Happy birthday!"],"collocations":["happy birthday","happy new year","happy life"],"synonyms":["glad","cheerful","joyful"],"antonyms":["sad","unhappy"],"keyword":"Happy=海皮(谐音)","image":"😊","topic":"emotions","grade":"chuyi-shang","frequency":4380,"difficulty":1}
,
{"word":"sad","phonetic":"/sæd/","pos":"adj.","translation":"悲伤的","definition":"feeling unhappiness","root":"","family":["sadly","sadness"],"examples":["Don't be sad.","She feels sad.","It is a sad story."],"collocations":["sad face","sad news","feel sad"],"synonyms":["unhappy","sorrowful"],"antonyms":["happy","cheerful"],"keyword":"Sad=塞的(谐音)","image":"😢","topic":"emotions","grade":"chuyi-shang","frequency":4370,"difficulty":1}
,
{"word":"good","phonetic":"/ɡʊd/","pos":"adj.","translation":"好的","definition":"having positive qualities","root":"","family":["better","best"],"examples":["Good morning!","You are a good student.","This is good news."],"collocations":["good morning","good afternoon","good evening"],"synonyms":["fine","nice","great"],"antonyms":["bad","poor"],"keyword":"Good=古的(谐音)","image":"👍","topic":"daily-life","grade":"chuyi-shang","frequency":4360,"difficulty":1}
,
{"word":"bad","phonetic":"/bæd/","pos":"adj.","translation":"坏的;不好的","definition":"not good","root":"","family":["worse","worst"],"examples":["Bad luck!","It is a bad day.","Don't be a bad boy."],"collocations":["bad day","bad luck","bad news"],"synonyms":["evil","poor","awful"],"antonyms":["good","excellent"],"keyword":"Bad=败的(谐音)","image":"👎","topic":"daily-life","grade":"chuyi-shang","frequency":4350,"difficulty":1}
,
{"word":"big","phonetic":"/bɪɡ/","pos":"adj.","translation":"大的","definition":"large in size","root":"","family":["bigger","biggest"],"examples":["It is a big house.","She has big eyes.","Beijing is a big city."],"collocations":["big city","big house","big family"],"synonyms":["large","huge","great"],"antonyms":["small","tiny"],"keyword":"Big=比格(谐音)","image":"🐘","topic":"daily-life","grade":"chuyi-shang","frequency":4340,"difficulty":1}
,
{"word":"small","phonetic":"/smɔːl/","pos":"adj.","translation":"小的","definition":"little in size","root":"","family":["smaller","smallest"],"examples":["It is a small cat.","She has a small bag.","He is a small boy."],"collocations":["small house","small size","small town"],"synonyms":["little","tiny"],"antonyms":["big","large"],"keyword":"Small=思莫(谐音)","image":"🐭","topic":"daily-life","grade":"chuyi-shang","frequency":4330,"difficulty":1}
,
{"word":"hot","phonetic":"/hɒt/","pos":"adj.","translation":"热的;辣的","definition":"having high temperature","root":"","family":["hotter","hottest"],"examples":["It is hot today.","I like hot soup.","Hot weather."],"collocations":["hot weather","hot water","hot dog"],"synonyms":["warm","boiling"],"antonyms":["cold","cool"],"keyword":"Hot=浩特(谐音)","image":"🔥","topic":"weather","grade":"chuyi-shang","frequency":4320,"difficulty":1}
,
{"word":"cold","phonetic":"/kəʊld/","pos":"adj.","translation":"冷的;寒冷的","definition":"low in temperature","root":"","family":["colder","coldest"],"examples":["It is cold today.","I have a cold.","Cold water."],"collocations":["cold weather","cold water","catch a cold"],"synonyms":["cool","chilly","freezing"],"antonyms":["hot","warm"],"keyword":"Cold=扣的(谐音)","image":"🥶","topic":"weather","grade":"chuyi-shang","frequency":4310,"difficulty":1}
,
{"word":"warm","phonetic":"/wɔːrm/","pos":"adj.","translation":"温暖的","definition":"moderately hot","root":"","family":["warmer","warmest","warmth"],"examples":["It is warm today.","She has warm hands.","Warm clothes."],"collocations":["warm weather","warm welcome","warm heart"],"synonyms":["hot","mild"],"antonyms":["cold","cool"],"keyword":"Warm=沃姆(谐音)","image":"🌤️","topic":"weather","grade":"chuyi-shang","frequency":4300,"difficulty":1}
,
{"word":"cool","phonetic":"/kuːl/","pos":"adj.","translation":"凉爽的;酷的","definition":"moderately cold","root":"","family":["cooler","coolest","coolness"],"examples":["It is cool today.","That is cool!","Cool drink."],"collocations":["cool down","cool weather","cool breeze"],"synonyms":["cold","chilly"],"antonyms":["warm","hot"],"keyword":"Cool=苦欧(谐音)","image":"😎","topic":"weather","grade":"chuyi-shang","frequency":4290,"difficulty":1}
,
{"word":"new","phonetic":"/njuː/","pos":"adj.","translation":"新的","definition":"not existing before","root":"","family":["newer","newest","renew"],"examples":["I have a new book.","It is a new car.","New Year."],"collocations":["new year","new car","new life"],"synonyms":["fresh","modern"],"antonyms":["old","ancient"],"keyword":"New=牛(谐音)","image":"✨","topic":"daily-life","grade":"chuyi-shang","frequency":4280,"difficulty":1}
,
{"word":"old","phonetic":"/əʊld/","pos":"adj.","translation":"老的;旧的","definition":"having lived a long time","root":"","family":["older","oldest"],"examples":["He is an old man.","This is an old house.","Old friends."],"collocations":["old man","old house","old days"],"synonyms":["aged","ancient"],"antonyms":["new","young"],"keyword":"Old=欧的(谐音)","image":"👴","topic":"daily-life","grade":"chuyi-shang","frequency":4270,"difficulty":1}
,
{"word":"young","phonetic":"/jʌŋ/","pos":"adj.","translation":"年轻的","definition":"having lived a short time","root":"","family":["younger","youngest","youth"],"examples":["She is young.","He is a young boy.","Young people."],"collocations":["young man","young people","young lady"],"synonyms":["youthful","juvenile"],"antonyms":["old","aged"],"keyword":"Young=洋(谐音)","image":"👶","topic":"daily-life","grade":"chuyi-shang","frequency":4260,"difficulty":1}
,
{"word":"red","phonetic":"/red/","pos":"adj.","translation":"红色的","definition":"color of blood","root":"","family":["reddish","redness"],"examples":["The apple is red.","Red light.","I like red."],"collocations":["red light","red color","red face"],"synonyms":["crimson","scarlet"],"antonyms":[],"keyword":"Red=瑞德(谐音)","image":"🔴","topic":"colors-numbers","grade":"chuyi-shang","frequency":4250,"difficulty":1}
,
{"word":"blue","phonetic":"/bluː/","pos":"adj.","translation":"蓝色的","definition":"color of sky","root":"","family":["bluish","blueish"],"examples":["The sky is blue.","Blue eyes.","I feel blue."],"collocations":["blue sky","blue sea","light blue"],"synonyms":["azure"],"antonyms":[],"keyword":"Blue=布鲁(谐音)","image":"🔵","topic":"colors-numbers","grade":"chuyi-shang","frequency":4240,"difficulty":1}
,
{"word":"green","phonetic":"/ɡriːn/","pos":"adj.","translation":"绿色的","definition":"color of grass","root":"","family":["greenish","greenery"],"examples":["Grass is green.","Green tea.","Green light."],"collocations":["green tea","green light","green apple"],"synonyms":["emerald","verdant"],"antonyms":[],"keyword":"Green=格林(谐音)","image":"🟢","topic":"colors-numbers","grade":"chuyi-shang","frequency":4230,"difficulty":1}
,
{"word":"yellow","phonetic":"/ˈjeləʊ/","pos":"adj.","translation":"黄色的","definition":"color of the sun","root":"","family":["yellowish"],"examples":["The sun is yellow.","Yellow flowers.","Yellow jacket."],"collocations":["yellow light","yellow color","yellow flower"],"synonyms":["golden"],"antonyms":[],"keyword":"Yellow=叶楼(谐音)","image":"🟡","topic":"colors-numbers","grade":"chuyi-shang","frequency":4220,"difficulty":1}
,
{"word":"black","phonetic":"/blæk/","pos":"adj.","translation":"黑色的","definition":"color of coal","root":"","family":["blacken","blackness"],"examples":["Black hair.","Black and white.","It is black."],"collocations":["black and white","black hair","black bird"],"synonyms":["dark"],"antonyms":["white"],"keyword":"Black=布拉克(谐音)","image":"⚫","topic":"colors-numbers","grade":"chuyi-shang","frequency":4210,"difficulty":1}
,
{"word":"white","phonetic":"/waɪt/","pos":"adj.","translation":"白色的","definition":"color of snow","root":"","family":["whiten","whiteness"],"examples":["Snow is white.","White clouds.","White shirt."],"collocations":["white shirt","white house","black and white"],"synonyms":["pale","snowy"],"antonyms":["black","dark"],"keyword":"White=外特(谐音)","image":"⚪","topic":"colors-numbers","grade":"chuyi-shang","frequency":4200,"difficulty":1}
,
{"word":"one","phonetic":"/wʌn/","pos":"num.","translation":"一","definition":"the number 1","root":"","family":["first","once"],"examples":["I have one book.","One plus one is two.","One day."],"collocations":["one by one","one day","one of"],"synonyms":[],"antonyms":[],"keyword":"One=万(谐音)","image":"1️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4190,"difficulty":1}
,
{"word":"two","phonetic":"/tuː/","pos":"num.","translation":"二","definition":"the number 2","root":"","family":["twice","second"],"examples":["I have two cats.","Two plus two is four.","Two days."],"collocations":["two by two","two days","two people"],"synonyms":[],"antonyms":[],"keyword":"Two=兔(谐音)","image":"2️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4180,"difficulty":1}
,
{"word":"three","phonetic":"/θriː/","pos":"num.","translation":"三","definition":"the number 3","root":"","family":["third","thrice"],"examples":["I have three books.","Three plus three is six.","Three days."],"collocations":["three times","three people","three days"],"synonyms":[],"antonyms":[],"keyword":"Three=思瑞(谐音)","image":"3️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4170,"difficulty":1}
,
{"word":"four","phonetic":"/fɔːr/","pos":"num.","translation":"四","definition":"the number 4","root":"","family":["fourth"],"examples":["I have four pens.","Four seasons.","Four people."],"collocations":["four seasons","four people","four days"],"synonyms":[],"antonyms":[],"keyword":"Four=佛尔(谐音)","image":"4️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4160,"difficulty":1}
,
{"word":"five","phonetic":"/faɪv/","pos":"num.","translation":"五","definition":"the number 5","root":"","family":["fifth"],"examples":["I have five friends.","Five stars.","Five minutes."],"collocations":["five minutes","five days","five stars"],"synonyms":[],"antonyms":[],"keyword":"Five=法夫(谐音)","image":"5️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4150,"difficulty":1}
,
{"word":"six","phonetic":"/sɪks/","pos":"num.","translation":"六","definition":"the number 6","root":"","family":["sixth"],"examples":["Six apples.","Six o'clock.","Six people."],"collocations":["six o'clock","six people","six days"],"synonyms":[],"antonyms":[],"keyword":"Six=西克斯(谐音)","image":"6️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4140,"difficulty":1}
,
{"word":"seven","phonetic":"/ˈsevən/","pos":"num.","translation":"七","definition":"the number 7","root":"","family":["seventh"],"examples":["Seven days.","Seven colors.","Seven people."],"collocations":["seven days","seven colors","seven times"],"synonyms":[],"antonyms":[],"keyword":"Seven=塞文(谐音)","image":"7️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4130,"difficulty":1}
,
{"word":"eight","phonetic":"/eɪt/","pos":"num.","translation":"八","definition":"the number 8","root":"","family":["eighth"],"examples":["Eight o'clock.","Eight people.","Eight days."],"collocations":["eight o'clock","eight days","eight people"],"synonyms":[],"antonyms":[],"keyword":"Eight=诶特(谐音)","image":"8️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4120,"difficulty":1}
,
{"word":"nine","phonetic":"/naɪn/","pos":"num.","translation":"九","definition":"the number 9","root":"","family":["ninth"],"examples":["Nine lives.","Nine people.","Nine o'clock."],"collocations":["nine o'clock","nine people","nine days"],"synonyms":[],"antonyms":[],"keyword":"Nine=奈恩(谐音)","image":"9️⃣","topic":"colors-numbers","grade":"chuyi-shang","frequency":4110,"difficulty":1}
,
{"word":"ten","phonetic":"/ten/","pos":"num.","translation":"十","definition":"the number 10","root":"","family":["tenth"],"examples":["I have ten books.","Ten o'clock.","Ten people."],"collocations":["ten o'clock","ten people","ten years"],"synonyms":[],"antonyms":[],"keyword":"Ten=特恩(谐音)","image":"🔟","topic":"colors-numbers","grade":"chuyi-shang","frequency":4100,"difficulty":1}
,
{"word":"family","phonetic":"/ˈfæməli/","pos":"n.","translation":"家庭;家人","definition":"a group of related people","root":"fam(家)+-ily","family":["families","familiar"],"examples":["I love my family.","Family is important.","There are four people in my family."],"collocations":["my family","family name","family tree"],"synonyms":["household","relatives"],"antonyms":[],"keyword":"Family=发么力(谐音)","image":"👨‍👩‍👧‍👦","topic":"family","grade":"chuyi-shang","frequency":4090,"difficulty":1}
,
{"word":"mother","phonetic":"/ˈmʌðər/","pos":"n.","translation":"母亲","definition":"female parent","root":"","family":["mothers","motherly"],"examples":["My mother is a teacher.","I love my mother.","Mother's Day."],"collocations":["my mother","mother's day","mother tongue"],"synonyms":["mom","mum"],"antonyms":["father","dad"],"keyword":"Mother=妈泽(谐音)","image":"👩","topic":"family","grade":"chuyi-shang","frequency":4080,"difficulty":1}
,
{"word":"father","phonetic":"/ˈfɑːðər/","pos":"n.","translation":"父亲","definition":"male parent","root":"","family":["fathers","fatherly"],"examples":["My father is tall.","I love my father.","Father's Day."],"collocations":["my father","father's day","father and son"],"synonyms":["dad","papa"],"antonyms":["mother","mom"],"keyword":"Father=发泽(谐音)","image":"👨","topic":"family","grade":"chuyi-shang","frequency":4070,"difficulty":1}
,
{"word":"parent","phonetic":"/ˈpeərənt/","pos":"n.","translation":"父母","definition":"mother or father","root":"par(生)+-ent","family":["parents","parenting"],"examples":["My parents are kind.","Parents love their children.","All parents care about their kids."],"collocations":["my parents","parents meeting","loving parents"],"synonyms":["father","mother"],"antonyms":["child"],"keyword":"Parent=派润特(谐音)","image":"👨‍👩","topic":"family","grade":"chuyi-shang","frequency":4060,"difficulty":1}
,
{"word":"brother","phonetic":"/ˈbrʌðər/","pos":"n.","translation":"兄弟;哥哥;弟弟","definition":"male sibling","root":"","family":["brothers","brotherly"],"examples":["He is my brother.","I have two brothers.","Brother and sister."],"collocations":["my brother","older brother","younger brother"],"synonyms":["sibling"],"antonyms":["sister"],"keyword":"Brother=布拉泽(谐音)","image":"👦","topic":"family","grade":"chuyi-shang","frequency":4050,"difficulty":1}
,
{"word":"sister","phonetic":"/ˈsɪstər/","pos":"n.","translation":"姐妹","definition":"female sibling","root":"","family":["sisters","sisterly"],"examples":["She is my sister.","I have one sister.","Sister and brother."],"collocations":["my sister","older sister","younger sister"],"synonyms":["sibling"],"antonyms":["brother"],"keyword":"Sister=西斯特(谐音)","image":"👧","topic":"family","grade":"chuyi-shang","frequency":4040,"difficulty":1}
,
{"word":"friend","phonetic":"/frend/","pos":"n.","translation":"朋友","definition":"a person you like","root":"","family":["friends","friendly","friendship"],"examples":["He is my friend.","Best friends.","A friend in need."],"collocations":["good friend","best friend","my friend"],"synonyms":["companion","pal"],"antonyms":["enemy","stranger"],"keyword":"Friend=弗兰德(谐音)","image":"🤝","topic":"daily-life","grade":"chuyi-shang","frequency":4030,"difficulty":1}
,
{"word":"teacher","phonetic":"/ˈtiːtʃər/","pos":"n.","translation":"老师","definition":"a person who teaches","root":"teach+-er","family":["teachers"],"examples":["My teacher is kind.","She is a teacher.","English teacher."],"collocations":["my teacher","English teacher","good teacher"],"synonyms":["instructor","educator"],"antonyms":["student","pupil"],"keyword":"Teacher=踢去尔(谐音)","image":"👩‍🏫","topic":"school","grade":"chuyi-shang","frequency":4020,"difficulty":1}
,
{"word":"student","phonetic":"/ˈstjuːdənt/","pos":"n.","translation":"学生","definition":"a person who studies","root":"stud(y)+-ent","family":["students"],"examples":["I am a student.","Good students.","Student Union."],"collocations":["good student","student union","student life"],"synonyms":["pupil","learner"],"antonyms":["teacher"],"keyword":"Student=死丢的恩特(谐音)","image":"🎒","topic":"school","grade":"chuyi-shang","frequency":4010,"difficulty":1}
,
{"word":"class","phonetic":"/klɑːs/","pos":"n.","translation":"班级;课","definition":"a group of students","root":"","family":["classes","classroom"],"examples":["I am in Class 3.","Class begins at 8.","After class."],"collocations":["in class","after class","class mate"],"synonyms":["lesson","course"],"antonyms":[],"keyword":"Class=克拉斯(谐音)","image":"🏫","topic":"school","grade":"chuyi-shang","frequency":4000,"difficulty":1}
,
{"word":"classmate","phonetic":"/ˈklɑːsmeɪt/","pos":"n.","translation":"同学","definition":"a fellow student in the same class","root":"class+mate","family":["classmates"],"examples":["He is my classmate.","We are classmates.","Classmate love."],"collocations":["my classmate","old classmate","new classmate"],"synonyms":["schoolmate"],"antonyms":[],"keyword":"Classmate=克拉斯美特(谐音)","image":"👫","topic":"school","grade":"chuyi-shang","frequency":3990,"difficulty":1}
,
{"word":"school","phonetic":"/skuːl/","pos":"n.","translation":"学校","definition":"a place for learning","root":"","family":["schools","schooling"],"examples":["I go to school.","School begins at 8.","My school is big."],"collocations":["go to school","at school","school life"],"synonyms":["academy","institution"],"antonyms":[],"keyword":"School=思古(谐音)","image":"🏫","topic":"school","grade":"chuyi-shang","frequency":3980,"difficulty":1}
,
{"word":"book","phonetic":"/bʊk/","pos":"n.","translation":"书;书籍","definition":"a written work","root":"","family":["books"],"examples":["I read a book.","This is my book.","Open the book."],"collocations":["read a book","book store","picture book"],"synonyms":["volume","text"],"antonyms":[],"keyword":"Book=布克(谐音)","image":"📚","topic":"school","grade":"chuyi-shang","frequency":3970,"difficulty":1}
,
{"word":"pen","phonetic":"/pen/","pos":"n.","translation":"钢笔","definition":"a writing instrument","root":"","family":["pens"],"examples":["I have a pen.","This pen is red.","Pen and paper."],"collocations":["pen pal","pen friend","ball pen"],"synonyms":[],"antonyms":["pencil"],"keyword":"Pen=盼(谐音)","image":"🖊️","topic":"school","grade":"chuyi-shang","frequency":3960,"difficulty":1}
,
{"word":"pencil","phonetic":"/ˈpensl/","pos":"n.","translation":"铅笔","definition":"a writing tool with graphite","root":"pen+cil","family":["pencils"],"examples":["I have a pencil.","Pencil case.","Use a pencil."],"collocations":["pencil case","pencil box","sharp pencil"],"synonyms":[],"antonyms":["pen"],"keyword":"Pencil=盼搜(谐音)","image":"✏️","topic":"school","grade":"chuyi-shang","frequency":3950,"difficulty":1}
,
{"word":"desk","phonetic":"/desk/","pos":"n.","translation":"书桌","definition":"a piece of furniture to write at","root":"","family":["desks"],"examples":["This is my desk.","The desk is clean.","On the desk."],"collocations":["at the desk","on the desk","desk lamp"],"synonyms":["table"],"antonyms":[],"keyword":"Desk=戴斯克(谐音)","image":"🪑","topic":"school","grade":"chuyi-shang","frequency":3940,"difficulty":1}
,
{"word":"chair","phonetic":"/tʃeər/","pos":"n.","translation":"椅子","definition":"a seat for one person","root":"","family":["chairs"],"examples":["Sit on the chair.","This chair is soft.","A chair for you."],"collocations":["on the chair","in the chair","arm chair"],"synonyms":["seat"],"antonyms":[],"keyword":"Chair=切尔(谐音)","image":"🪑","topic":"daily-life","grade":"chuyi-shang","frequency":3930,"difficulty":1}
,
{"word":"table","phonetic":"/ˈteɪbl/","pos":"n.","translation":"桌子;表格","definition":"a piece of furniture","root":"","family":["tables"],"examples":["On the table.","A round table.","Dinner table."],"collocations":["on the table","dinner table","table tennis"],"synonyms":["desk"],"antonyms":[],"keyword":"Table=特波(谐音)","image":"🪑","topic":"daily-life","grade":"chuyi-shang","frequency":3920,"difficulty":1}
,
{"word":"door","phonetic":"/dɔːr/","pos":"n.","translation":"门","definition":"an opening to enter a room","root":"","family":["doors"],"examples":["Open the door.","Close the door.","The door is white."],"collocations":["open the door","at the door","back door"],"synonyms":["gate","entrance"],"antonyms":["window"],"keyword":"Door=多尔(谐音)","image":"🚪","topic":"daily-life","grade":"chuyi-shang","frequency":3910,"difficulty":1}
,
{"word":"window","phonetic":"/ˈwɪndəʊ/","pos":"n.","translation":"窗户","definition":"an opening in a wall for light","root":"wind(风)+ow","family":["windows"],"examples":["Open the window.","The window is closed.","Look out the window."],"collocations":["open the window","by the window","window seat"],"synonyms":[],"antonyms":["wall"],"keyword":"Window=温兜(谐音)","image":"🪟","topic":"places","grade":"chuyi-shang","frequency":3900,"difficulty":1}
,
{"word":"wall","phonetic":"/wɔːl/","pos":"n.","translation":"墙","definition":"a vertical structure","root":"","family":["walls"],"examples":["On the wall.","Wall paper.","The wall is white."],"collocations":["on the wall","wall paper","stone wall"],"synonyms":["partition"],"antonyms":[],"keyword":"Wall=沃尔(谐音)","image":"🧱","topic":"places","grade":"chuyi-shang","frequency":3890,"difficulty":1}
,
{"word":"floor","phonetic":"/flɔːr/","pos":"n.","translation":"地板;楼层","definition":"the bottom surface of a room","root":"","family":["floors","flooring"],"examples":["On the floor.","First floor.","The floor is clean."],"collocations":["on the floor","first floor","second floor"],"synonyms":["ground"],"antonyms":["ceiling"],"keyword":"Floor=弗洛尔(谐音)","image":"🟫","topic":"places","grade":"chuyi-shang","frequency":3880,"difficulty":1}
,
{"word":"room","phonetic":"/ruːm/","pos":"n.","translation":"房间","definition":"a space in a building","root":"","family":["rooms"],"examples":["My room is small.","Living room.","Bed room."],"collocations":["living room","bed room","in the room"],"synonyms":["chamber"],"antonyms":[],"keyword":"Room=如姆(谐音)","image":"🏠","topic":"places","grade":"chuyi-shang","frequency":3870,"difficulty":1}
,
{"word":"home","phonetic":"/həʊm/","pos":"n.","translation":"家","definition":"the place where one lives","root":"","family":["homes","homeless","homework"],"examples":["I go home.","Welcome home.","Home sweet home."],"collocations":["go home","at home","home work"],"synonyms":["house","residence"],"antonyms":[],"keyword":"Home=后姆(谐音)","image":"🏠","topic":"family","grade":"chuyi-shang","frequency":3860,"difficulty":1}
,
{"word":"house","phonetic":"/haʊs/","pos":"n.","translation":"房子","definition":"a building for living","root":"","family":["houses","housing"],"examples":["A big house.","This is my house.","House number."],"collocations":["my house","at the house","house work"],"synonyms":["home","dwelling"],"antonyms":[],"keyword":"House=好斯(谐音)","image":"🏠","topic":"places","grade":"chuyi-shang","frequency":3850,"difficulty":1}
,
{"word":"cat","phonetic":"/kæt/","pos":"n.","translation":"猫","definition":"a small furry pet","root":"","family":["cats","kitty"],"examples":["I have a cat.","The cat is cute.","Black cat."],"collocations":["cat and dog","cat food","wild cat"],"synonyms":["kitten"],"antonyms":["dog"],"keyword":"Cat=凯特(谐音)","image":"🐱","topic":"animals","grade":"chuyi-shang","frequency":3840,"difficulty":1}
,
{"word":"dog","phonetic":"/dɒɡ/","pos":"n.","translation":"狗","definition":"a common pet animal","root":"","family":["dogs","doggy"],"examples":["A big dog.","My dog is white.","Lucky dog."],"collocations":["hot dog","dog food","guard dog"],"synonyms":["puppy"],"antonyms":["cat"],"keyword":"Dog=道格(谐音)","image":"🐶","topic":"animals","grade":"chuyi-shang","frequency":3830,"difficulty":1}
,
{"word":"bird","phonetic":"/bɜːrd/","pos":"n.","translation":"鸟","definition":"a creature with wings and feathers","root":"","family":["birds"],"examples":["A bird flies.","Beautiful bird.","Birds sing."],"collocations":["bird song","bird watching","sea bird"],"synonyms":["fowl"],"antonyms":[],"keyword":"Bird=博德(谐音)","image":"🐦","topic":"animals","grade":"chuyi-shang","frequency":3820,"difficulty":1}
,
{"word":"fish","phonetic":"/fɪʃ/","pos":"n.","translation":"鱼","definition":"an animal that lives in water","root":"","family":["fishes","fishing"],"examples":["I like fish.","Go fishing.","Fish and chips."],"collocations":["go fishing","fish tank","big fish"],"synonyms":[],"antonyms":[],"keyword":"Fish=费什(谐音)","image":"🐟","topic":"animals","grade":"chuyi-shang","frequency":3810,"difficulty":1}
,
{"word":"apple","phonetic":"/ˈæpl/","pos":"n.","translation":"苹果","definition":"a round red fruit","root":"","family":["apples"],"examples":["I eat an apple.","Apple pie.","Red apple."],"collocations":["apple tree","apple juice","apple pie"],"synonyms":[],"antonyms":[],"keyword":"Apple=爱普(谐音)","image":"🍎","topic":"food","grade":"chuyi-shang","frequency":3800,"difficulty":1}
,
{"word":"banana","phonetic":"/bəˈnɑːnə/","pos":"n.","translation":"香蕉","definition":"a long yellow fruit","root":"","family":["bananas"],"examples":["A banana.","I like bananas.","Banana cake."],"collocations":["banana cake","banana split","ripe banana"],"synonyms":[],"antonyms":[],"keyword":"Banana=吧那那(谐音)","image":"🍌","topic":"food","grade":"chuyi-shang","frequency":3790,"difficulty":1}
,
{"word":"orange","phonetic":"/ˈɒrɪndʒ/","pos":"n.","translation":"橙子;橙色","definition":"a round citrus fruit","root":"","family":["oranges"],"examples":["An orange.","Orange juice.","I like oranges."],"collocations":["orange juice","orange color","orange tree"],"synonyms":[],"antonyms":[],"keyword":"Orange=奥润季(谐音)","image":"🍊","topic":"food","grade":"chuyi-shang","frequency":3780,"difficulty":1}
,
{"word":"milk","phonetic":"/mɪlk/","pos":"n.","translation":"牛奶","definition":"white liquid from cows","root":"","family":[],"examples":["Drink milk.","I like milk.","Milk shake."],"collocations":["drink milk","milk shake","fresh milk"],"synonyms":[],"antonyms":[],"keyword":"Milk=某欧克(谐音)","image":"🥛","topic":"food","grade":"chuyi-shang","frequency":3770,"difficulty":1}
,
{"word":"water","phonetic":"/ˈwɔːtər/","pos":"n.","translation":"水","definition":"clear liquid","root":"","family":["waters","waterfall"],"examples":["Drink water.","Cold water.","Water the flowers."],"collocations":["drink water","cold water","hot water"],"synonyms":[],"antonyms":[],"keyword":"Water=沃特(谐音)","image":"💧","topic":"food","grade":"chuyi-shang","frequency":3760,"difficulty":1}
,
{"word":"tea","phonetic":"/tiː/","pos":"n.","translation":"茶","definition":"a hot drink made from leaves","root":"","family":["teas"],"examples":["A cup of tea.","I like tea.","Green tea."],"collocations":["green tea","black tea","drink tea"],"synonyms":[],"antonyms":[],"keyword":"Tea=提(谐音)","image":"🍵","topic":"food","grade":"chuyi-shang","frequency":3750,"difficulty":1}
,
{"word":"rice","phonetic":"/raɪs/","pos":"n.","translation":"米饭;大米","definition":"a cereal grain","root":"","family":["rices"],"examples":["Eat rice.","Rice bowl.","Fried rice."],"collocations":["fried rice","rice bowl","rice cake"],"synonyms":[],"antonyms":[],"keyword":"Rice=瑞斯(谐音)","image":"🍚","topic":"food","grade":"chuyi-shang","frequency":3740,"difficulty":1}
,
{"word":"bread","phonetic":"/bred/","pos":"n.","translation":"面包","definition":"a baked food made of flour","root":"","family":["breads"],"examples":["Eat bread.","Bread and butter.","Fresh bread."],"collocations":["bread and butter","bake bread","whole bread"],"synonyms":["loaf"],"antonyms":[],"keyword":"Bread=布瑞德(谐音)","image":"🍞","topic":"food","grade":"chuyi-shang","frequency":3730,"difficulty":1}
,
{"word":"egg","phonetic":"/eɡ/","pos":"n.","translation":"鸡蛋;蛋","definition":"an oval object from birds","root":"","family":["eggs"],"examples":["An egg.","Egg and milk.","Fried egg."],"collocations":["egg yolk","egg white","lay an egg"],"synonyms":[],"antonyms":[],"keyword":"Egg=诶格(谐音)","image":"🥚","topic":"food","grade":"chuyi-shang","frequency":3720,"difficulty":1}
,
{"word":"cake","phonetic":"/keɪk/","pos":"n.","translation":"蛋糕","definition":"a sweet baked food","root":"","family":["cakes"],"examples":["Birthday cake.","I love cake.","Make a cake."],"collocations":["birthday cake","make a cake","moon cake"],"synonyms":[],"antonyms":[],"keyword":"Cake=凯克(谐音)","image":"🍰","topic":"food","grade":"chuyi-shang","frequency":3710,"difficulty":1}
,
{"word":"sweet","phonetic":"/swiːt/","pos":"adj.","translation":"甜的;甜的","definition":"tasting like sugar","root":"","family":["sweetly","sweetness"],"examples":["Sweet candy.","She is sweet.","Sweet dreams."],"collocations":["sweet dreams","sweet heart","sweet home"],"synonyms":["sugary"],"antonyms":["sour","bitter"],"keyword":"Sweet=思未特(谐音)","image":"🍬","topic":"food","grade":"chuyi-shang","frequency":3700,"difficulty":1}
,
{"word":"bus","phonetic":"/bʌs/","pos":"n.","translation":"公共汽车","definition":"a large motor vehicle","root":"","family":["buses"],"examples":["By bus.","School bus.","Take a bus."],"collocations":["by bus","school bus","bus stop"],"synonyms":["coach"],"antonyms":[],"keyword":"Bus=巴斯(谐音)","image":"🚌","topic":"travel","grade":"chuyi-shang","frequency":3690,"difficulty":1}
,
{"word":"car","phonetic":"/kɑːr/","pos":"n.","translation":"汽车;轿车","definition":"a motor vehicle","root":"","family":["cars"],"examples":["A red car.","By car.","Drive a car."],"collocations":["by car","red car","new car"],"synonyms":["vehicle","auto"],"antonyms":[],"keyword":"Car=卡尔(谐音)","image":"🚗","topic":"travel","grade":"chuyi-shang","frequency":3680,"difficulty":1}
,
{"word":"bike","phonetic":"/baɪk/","pos":"n.","translation":"自行车","definition":"a two-wheeled vehicle","root":"","family":["bikes","biking"],"examples":["By bike.","Ride a bike.","New bike."],"collocations":["by bike","ride a bike","mountain bike"],"synonyms":["bicycle"],"antonyms":[],"keyword":"Bike=拜克(谐音)","image":"🚲","topic":"travel","grade":"chuyi-shang","frequency":3670,"difficulty":1}
,
{"word":"train","phonetic":"/treɪn/","pos":"n.","translation":"火车","definition":"a series of connected railway cars","root":"","family":["trains"],"examples":["By train.","Take a train.","Train station."],"collocations":["by train","take a train","train station"],"synonyms":[],"antonyms":[],"keyword":"Train=追恩(谐音)","image":"🚆","topic":"travel","grade":"chuyi-shang","frequency":3660,"difficulty":1}
,
{"word":"park","phonetic":"/pɑːrk/","pos":"n.","translation":"公园","definition":"a public green area","root":"","family":["parks"],"examples":["In the park.","Park the car.","Go to the park."],"collocations":["in the park","park the car","national park"],"synonyms":["garden"],"antonyms":[],"keyword":"Park=派克(谐音)","image":"🏞️","topic":"places","grade":"chuyi-shang","frequency":3650,"difficulty":1}
,
{"word":"shop","phonetic":"/ʃɒp/","pos":"n.","translation":"商店","definition":"a store","root":"","family":["shops","shopping"],"examples":["Go shopping.","At the shop.","Coffee shop."],"collocations":["go shopping","coffee shop","shop keeper"],"synonyms":["store"],"antonyms":[],"keyword":"Shop=肖普(谐音)","image":"🛍️","topic":"places","grade":"chuyi-shang","frequency":3640,"difficulty":1}
,
{"word":"store","phonetic":"/stɔːr/","pos":"n.","translation":"商店;储存","definition":"a shop or warehouse","root":"","family":["stores"],"examples":["At the store.","Store the food.","Book store."],"collocations":["book store","department store","in store"],"synonyms":["shop"],"antonyms":[],"keyword":"Store=斯道尔(谐音)","image":"🏪","topic":"places","grade":"chuyi-shang","frequency":3630,"difficulty":1}
,
{"word":"street","phonetic":"/striːt/","pos":"n.","translation":"街道","definition":"a public road in a city","root":"","family":["streets"],"examples":["On the street.","Main street.","Busy street."],"collocations":["on the street","main street","street light"],"synonyms":["road","avenue"],"antonyms":[],"keyword":"Street=思追特(谐音)","image":"🛣️","topic":"places","grade":"chuyi-shang","frequency":3620,"difficulty":1}
,
{"word":"city","phonetic":"/ˈsɪti/","pos":"n.","translation":"城市","definition":"a large town","root":"cit+-y","family":["cities"],"examples":["A big city.","In the city.","City life."],"collocations":["big city","city life","in the city"],"synonyms":["town","metropolis"],"antonyms":["village","country"],"keyword":"City=西提(谐音)","image":"🏙️","topic":"places","grade":"chuyi-shang","frequency":3610,"difficulty":1}
,
{"word":"town","phonetic":"/taʊn/","pos":"n.","translation":"城镇","definition":"a small city","root":"","family":["towns"],"examples":["A small town.","Town square.","Go to town."],"collocations":["small town","in town","town hall"],"synonyms":["city"],"antonyms":["village"],"keyword":"Town=汤(谐音)","image":"🏘️","topic":"places","grade":"chuyi-shang","frequency":3600,"difficulty":1}
,
{"word":"village","phonetic":"/ˈvɪlɪdʒ/","pos":"n.","translation":"村庄","definition":"a small countryside community","root":"vill+age","family":["villages"],"examples":["A small village.","In the village.","Village life."],"collocations":["small village","in the village","village life"],"synonyms":["hamlet"],"antonyms":["city"],"keyword":"Village=威力季(谐音)","image":"🏡","topic":"places","grade":"chuyi-shang","frequency":3590,"difficulty":1}
,
{"word":"country","phonetic":"/ˈkʌntri/","pos":"n.","translation":"国家;乡村","definition":"a nation or rural area","root":"count+-ry","family":["countries"],"examples":["My country.","Country music.","Country life."],"collocations":["my country","country life","native country"],"synonyms":["nation","state"],"antonyms":[],"keyword":"Country=肯特瑞(谐音)","image":"🌍","topic":"places","grade":"chuyi-shang","frequency":3580,"difficulty":1}
,
{"word":"China","phonetic":"/ˈtʃaɪnə/","pos":"n.","translation":"中国","definition":"a country in East Asia","root":"","family":[],"examples":["I live in China.","China is big.","Made in China."],"collocations":["in China","from China","China Town"],"synonyms":[],"antonyms":[],"keyword":"China=柴那(谐音)","image":"🇨🇳","topic":"places","grade":"chuyi-shang","frequency":3570,"difficulty":1}
,
{"word":"world","phonetic":"/wɜːrld/","pos":"n.","translation":"世界","definition":"the earth and all life","root":"","family":["worlds"],"examples":["Around the world.","World peace.","The world is big."],"collocations":["around the world","in the world","world cup"],"synonyms":["earth","globe"],"antonyms":[],"keyword":"World=沃德(谐音)","image":"🌐","topic":"places","grade":"chuyi-shang","frequency":3560,"difficulty":1}
,
{"word":"morning","phonetic":"/ˈmɔːrnɪŋ/","pos":"n.","translation":"早晨;上午","definition":"early part of the day","root":"morn+-ing","family":["mornings"],"examples":["Good morning.","In the morning.","Every morning."],"collocations":["good morning","in the morning","every morning"],"synonyms":["dawn","am"],"antonyms":["evening","night"],"keyword":"Morning=莫宁(谐音)","image":"🌅","topic":"time","grade":"chuyi-shang","frequency":3550,"difficulty":1}
,
{"word":"afternoon","phonetic":"/ˌɑːftərˈnuːn/","pos":"n.","translation":"下午","definition":"time between noon and evening","root":"after+noon","family":["afternoons"],"examples":["Good afternoon.","In the afternoon.","This afternoon."],"collocations":["good afternoon","in the afternoon","this afternoon"],"synonyms":[],"antonyms":["morning"],"keyword":"Afternoon=啊福特怒恩(谐音)","image":"☀️","topic":"time","grade":"chuyi-shang","frequency":3540,"difficulty":1}
,
{"word":"evening","phonetic":"/ˈiːvnɪŋ/","pos":"n.","translation":"傍晚;晚上","definition":"end of the day","root":"even+-ing","family":["evenings"],"examples":["Good evening.","In the evening.","This evening."],"collocations":["good evening","in the evening","this evening"],"synonyms":["dusk","night"],"antonyms":["morning"],"keyword":"Evening=衣文宁(谐音)","image":"🌆","topic":"time","grade":"chuyi-shang","frequency":3530,"difficulty":1}
,
{"word":"night","phonetic":"/naɪt/","pos":"n.","translation":"夜晚;夜间","definition":"time when it's dark","root":"","family":["nights"],"examples":["Good night.","At night.","Star night."],"collocations":["good night","at night","night and day"],"synonyms":["midnight"],"antonyms":["day"],"keyword":"Night=奈特(谐音)","image":"🌃","topic":"time","grade":"chuyi-shang","frequency":3520,"difficulty":1}
,
{"word":"day","phonetic":"/deɪ/","pos":"n.","translation":"白天;一天","definition":"time from sunrise to sunset","root":"","family":["days"],"examples":["Good day.","Every day.","All day."],"collocations":["every day","all day","school day"],"synonyms":["daytime"],"antonyms":["night"],"keyword":"Day=戴(谐音)","image":"🌞","topic":"time","grade":"chuyi-shang","frequency":3510,"difficulty":1}
,
{"word":"today","phonetic":"/təˈdeɪ/","pos":"n.","translation":"今天","definition":"this day","root":"to+day","family":[],"examples":["Today is Monday.","See you today.","Today's news."],"collocations":["today is","today's","today and tomorrow"],"synonyms":[],"antonyms":[],"keyword":"Today=特戴(谐音)","image":"📅","topic":"time","grade":"chuyi-shang","frequency":3500,"difficulty":1}
,
{"word":"tomorrow","phonetic":"/təˈmɒrəʊ/","pos":"n.","translation":"明天","definition":"the day after today","root":"to+morrow","family":["tomorrows"],"examples":["See you tomorrow.","Tomorrow will be better.","Tomorrow's plan."],"collocations":["see you tomorrow","tomorrow morning","tomorrow afternoon"],"synonyms":[],"antonyms":["yesterday"],"keyword":"Tomorrow=特摩柔(谐音)","image":"📅","topic":"time","grade":"chuyi-shang","frequency":3490,"difficulty":1}
,
{"word":"yesterday","phonetic":"/ˈjestədeɪ/","pos":"n.","translation":"昨天","definition":"the day before today","root":"yester+day","family":["yesterdays"],"examples":["Yesterday was Monday.","I saw him yesterday.","Yesterday's news."],"collocations":["yesterday morning","yesterday afternoon","yesterday evening"],"synonyms":[],"antonyms":["tomorrow"],"keyword":"Yesterday=耶斯特戴(谐音)","image":"📅","topic":"time","grade":"chuyi-shang","frequency":3480,"difficulty":1}
,
{"word":"week","phonetic":"/wiːk/","pos":"n.","translation":"星期;周","definition":"a period of seven days","root":"","family":["weeks"],"examples":["This week.","Last week.","Next week."],"collocations":["this week","last week","next week"],"synonyms":["seven days"],"antonyms":[],"keyword":"Week=未克(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3470,"difficulty":1}
,
{"word":"month","phonetic":"/mʌnθ/","pos":"n.","translation":"月;月份","definition":"a period of about 30 days","root":"","family":["months"],"examples":["This month.","Last month.","Next month."],"collocations":["this month","last month","every month"],"synonyms":[],"antonyms":[],"keyword":"Month=忙斯(谐音)","image":"🗓️","topic":"time","grade":"chuyi-shang","frequency":3460,"difficulty":1}
,
{"word":"year","phonetic":"/jɪər/","pos":"n.","translation":"年;年份","definition":"a period of 12 months","root":"","family":["years"],"examples":["This year.","Happy new year.","Last year."],"collocations":["this year","last year","new year"],"synonyms":["annum"],"antonyms":[],"keyword":"Year=叶尔(谐音)","image":"🎊","topic":"time","grade":"chuyi-shang","frequency":3450,"difficulty":1}
,
{"word":"time","phonetic":"/taɪm/","pos":"n.","translation":"时间;次数","definition":"a period or moment","root":"","family":["times"],"examples":["What time is it?","Have a good time.","Time flies."],"collocations":["what time","have time","on time"],"synonyms":["moment","period"],"antonyms":[],"keyword":"Time=太姆(谐音)","image":"⏰","topic":"time","grade":"chuyi-shang","frequency":3440,"difficulty":1}
,
{"word":"o'clock","phonetic":"/əˈklɒk/","pos":"n.","translation":"点钟","definition":"used for exact hour","root":"of+clock","family":[],"examples":["It is 5 o'clock.","Three o'clock.","At 8 o'clock."],"collocations":["o'clock at","o'clock in","sharp o'clock"],"synonyms":[],"antonyms":[],"keyword":"O'clock=欧克拉克(谐音)","image":"🕐","topic":"time","grade":"chuyi-shang","frequency":3430,"difficulty":1}
,
{"word":"hour","phonetic":"/aʊər/","pos":"n.","translation":"小时","definition":"a period of 60 minutes","root":"","family":["hours"],"examples":["One hour.","Half an hour.","After hours."],"collocations":["half an hour","one hour","hour after"],"synonyms":["60 minutes"],"antonyms":[],"keyword":"Hour=奥尔(谐音)","image":"⏱️","topic":"time","grade":"chuyi-shang","frequency":3420,"difficulty":1}
,
{"word":"minute","phonetic":"/ˈmɪnɪt/","pos":"n.","translation":"分钟","definition":"a period of 60 seconds","root":"","family":["minutes"],"examples":["Wait a minute.","In a minute.","Five minutes."],"collocations":["wait a minute","a minute ago","for a minute"],"synonyms":["60 seconds"],"antonyms":[],"keyword":"Minute=米尼特(谐音)","image":"⏱️","topic":"time","grade":"chuyi-shang","frequency":3410,"difficulty":1}
,
{"word":"Monday","phonetic":"/ˈmʌndeɪ/","pos":"n.","translation":"星期一","definition":"first day of week","root":"","family":[],"examples":["Today is Monday.","On Monday.","Monday morning."],"collocations":["on Monday","Monday morning","Monday evening"],"synonyms":[],"antonyms":[],"keyword":"Monday=蛮戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3400,"difficulty":1}
,
{"word":"Tuesday","phonetic":"/ˈtjuːzdeɪ/","pos":"n.","translation":"星期二","definition":"second day of week","root":"","family":[],"examples":["On Tuesday.","Tuesday afternoon.","Tuesday morning."],"collocations":["on Tuesday","this Tuesday","Tuesday meeting"],"synonyms":[],"antonyms":[],"keyword":"Tuesday=秋斯戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3390,"difficulty":1}
,
{"word":"Wednesday","phonetic":"/ˈwenzdeɪ/","pos":"n.","translation":"星期三","definition":"third day of week","root":"","family":[],"examples":["On Wednesday.","Wednesday class.","This Wednesday."],"collocations":["on Wednesday","this Wednesday","next Wednesday"],"synonyms":[],"antonyms":[],"keyword":"Wednesday=温斯戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3380,"difficulty":1}
,
{"word":"Thursday","phonetic":"/ˈθɜːrzdeɪ/","pos":"n.","translation":"星期四","definition":"fourth day of week","root":"","family":[],"examples":["On Thursday.","Thursday morning.","This Thursday."],"collocations":["on Thursday","this Thursday","next Thursday"],"synonyms":[],"antonyms":[],"keyword":"Thursday=色斯戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3370,"difficulty":1}
,
{"word":"Friday","phonetic":"/ˈfraɪdeɪ/","pos":"n.","translation":"星期五","definition":"fifth day of week","root":"","family":[],"examples":["On Friday.","Friday afternoon.","TGIF Friday."],"collocations":["on Friday","Friday night","this Friday"],"synonyms":[],"antonyms":[],"keyword":"Friday=夫瑞戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3360,"difficulty":1}
,
{"word":"Saturday","phonetic":"/ˈsætərdeɪ/","pos":"n.","translation":"星期六","definition":"sixth day of week","root":"","family":[],"examples":["On Saturday.","Saturday morning.","This Saturday."],"collocations":["on Saturday","this Saturday","Saturday night"],"synonyms":[],"antonyms":[],"keyword":"Saturday=塞特戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3350,"difficulty":1}
,
{"word":"Sunday","phonetic":"/ˈsʌndeɪ/","pos":"n.","translation":"星期日","definition":"first day of week","root":"","family":[],"examples":["On Sunday.","Sunday morning.","This Sunday."],"collocations":["on Sunday","this Sunday","Sunday school"],"synonyms":[],"antonyms":[],"keyword":"Sunday=桑戴(谐音)","image":"📆","topic":"time","grade":"chuyi-shang","frequency":3340,"difficulty":1}
,
{"word":"spring","phonetic":"/sprɪŋ/","pos":"n.","translation":"春天;弹簧","definition":"the season after winter","root":"","family":["springs"],"examples":["In spring.","Spring flowers.","Spring Festival."],"collocations":["in spring","spring time","spring water"],"synonyms":["springtime"],"antonyms":["autumn","fall"],"keyword":"Spring=思扑瑞英(谐音)","image":"🌸","topic":"time","grade":"chuyi-shang","frequency":3330,"difficulty":1}
,
{"word":"summer","phonetic":"/ˈsʌmər/","pos":"n.","translation":"夏天","definition":"the hot season","root":"","family":["summers"],"examples":["In summer.","Summer holiday.","Hot summer."],"collocations":["in summer","summer holiday","summer camp"],"synonyms":["summertime"],"antonyms":["winter"],"keyword":"Summer=萨么(谐音)","image":"☀️","topic":"time","grade":"chuyi-shang","frequency":3320,"difficulty":1}
,
{"word":"autumn","phonetic":"/ˈɔːtəm/","pos":"n.","translation":"秋天","definition":"the season between summer and winter","root":"","family":["autumns"],"examples":["In autumn.","Autumn leaves.","Cool autumn."],"collocations":["in autumn","autumn leaves","mid autumn"],"synonyms":["fall"],"antonyms":["spring"],"keyword":"Autumn=奥特姆(谐音)","image":"🍂","topic":"time","grade":"chuyi-shang","frequency":3310,"difficulty":1}
,
{"word":"winter","phonetic":"/ˈwɪntər/","pos":"n.","translation":"冬天","definition":"the cold season","root":"","family":["winters"],"examples":["In winter.","Cold winter.","Winter vacation."],"collocations":["in winter","winter vacation","winter sports"],"synonyms":[],"antonyms":["summer"],"keyword":"Winter=温特(谐音)","image":"❄️","topic":"time","grade":"chuyi-shang","frequency":3300,"difficulty":1}
,
{"word":"sun","phonetic":"/sʌn/","pos":"n.","translation":"太阳","definition":"the star of the solar system","root":"","family":["sunny","sunshine"],"examples":["The sun is hot.","Sun shines.","Sun rise."],"collocations":["the sun","sun rise","sun set"],"synonyms":["star"],"antonyms":[],"keyword":"Sun=桑(谐音)","image":"☀️","topic":"weather","grade":"chuyi-shang","frequency":3290,"difficulty":1}
,
{"word":"moon","phonetic":"/muːn/","pos":"n.","translation":"月亮","definition":"earth's natural satellite","root":"","family":["moons","moonlight"],"examples":["The moon.","Moon cake.","Full moon."],"collocations":["full moon","moon light","moon cake"],"synonyms":[],"antonyms":[],"keyword":"Moon=木恩(谐音)","image":"🌙","topic":"nature","grade":"chuyi-shang","frequency":3280,"difficulty":1}
,
{"word":"star","phonetic":"/stɑːr/","pos":"n.","translation":"星星","definition":"a celestial body","root":"","family":["stars","starlight"],"examples":["Star light.","Bright stars.","Pop star."],"collocations":["star light","movie star","pop star"],"synonyms":[],"antonyms":[],"keyword":"Star=斯达(谐音)","image":"⭐","topic":"nature","grade":"chuyi-shang","frequency":3270,"difficulty":1}
,
{"word":"sky","phonetic":"/skaɪ/","pos":"n.","translation":"天空","definition":"the expanse above","root":"","family":["skies"],"examples":["Blue sky.","Sky high.","Up to the sky."],"collocations":["blue sky","sky blue","in the sky"],"synonyms":["heaven"],"antonyms":[],"keyword":"Sky=思盖(谐音)","image":"🌌","topic":"nature","grade":"chuyi-shang","frequency":3260,"difficulty":1}
,
{"word":"cloud","phonetic":"/klaʊd/","pos":"n.","translation":"云","definition":"a white mass in the sky","root":"","family":["clouds","cloudy"],"examples":["White clouds.","Cloudy day.","In the clouds."],"collocations":["white clouds","cloud nine","in the clouds"],"synonyms":[],"antonyms":[],"keyword":"Cloud=克老德(谐音)","image":"☁️","topic":"weather","grade":"chuyi-shang","frequency":3250,"difficulty":1}
,
{"word":"rain","phonetic":"/reɪn/","pos":"n.","translation":"雨","definition":"water falling from clouds","root":"","family":["rains","rainy"],"examples":["It is raining.","Heavy rain.","Rain drop."],"collocations":["heavy rain","rain coat","rain bow"],"synonyms":["rainfall"],"antonyms":[],"keyword":"Rain=瑞恩(谐音)","image":"🌧️","topic":"weather","grade":"chuyi-shang","frequency":3240,"difficulty":1}
,
{"word":"wind","phonetic":"/wɪnd/","pos":"n.","translation":"风","definition":"moving air","root":"","family":["winds","windy"],"examples":["Strong wind.","Cold wind.","Wind blows."],"collocations":["strong wind","cold wind","wind mill"],"synonyms":["breeze","gust"],"antonyms":[],"keyword":"Wind=温德(谐音)","image":"🌬️","topic":"weather","grade":"chuyi-shang","frequency":3230,"difficulty":1}
,
{"word":"snow","phonetic":"/snəʊ/","pos":"n.","translation":"雪","definition":"frozen precipitation","root":"","family":["snows","snowy"],"examples":["White snow.","Snow man.","Snow falls."],"collocations":["snow man","snow ball","snow white"],"synonyms":[],"antonyms":[],"keyword":"Snow=思诺(谐音)","image":"❄️","topic":"weather","grade":"chuyi-shang","frequency":3220,"difficulty":1}
,
{"word":"tree","phonetic":"/triː/","pos":"n.","translation":"树;树木","definition":"a tall plant","root":"","family":["trees"],"examples":["A tall tree.","Tree house.","Apple tree."],"collocations":["apple tree","tree house","family tree"],"synonyms":[],"antonyms":[],"keyword":"Tree=追(谐音)","image":"🌳","topic":"nature","grade":"chuyi-shang","frequency":3210,"difficulty":1}
,
{"word":"flower","phonetic":"/ˈflaʊər/","pos":"n.","translation":"花;花朵","definition":"the colored part of a plant","root":"flour+-er","family":["flowers"],"examples":["Beautiful flowers.","Flower garden.","Spring flowers."],"collocations":["flower garden","flower shop","beautiful flower"],"synonyms":["bloom"],"antonyms":[],"keyword":"Flower=弗劳尔(谐音)","image":"🌸","topic":"nature","grade":"chuyi-shang","frequency":3200,"difficulty":1}
,
{"word":"grass","phonetic":"/ɡrɑːs/","pos":"n.","translation":"草;草地","definition":"a plant with thin leaves","root":"","family":["grasses","grassy"],"examples":["Green grass.","Cut the grass.","Grass land."],"collocations":["green grass","grass land","grasshopper"],"synonyms":["lawn","turf"],"antonyms":[],"keyword":"Grass=格拉斯(谐音)","image":"🌱","topic":"nature","grade":"chuyi-shang","frequency":3190,"difficulty":1}
,
{"word":"mountain","phonetic":"/ˈmaʊntən/","pos":"n.","translation":"山;山脉","definition":"a high landform","root":"mount+-ain","family":["mountains"],"examples":["High mountains.","Mountain top.","In the mountain."],"collocations":["mountain top","mountain climbing","high mountain"],"synonyms":["peak","hill"],"antonyms":["valley"],"keyword":"Mountain=曼腾(谐音)","image":"⛰️","topic":"nature","grade":"chuyi-shang","frequency":3180,"difficulty":1}
,
{"word":"river","phonetic":"/ˈrɪvər/","pos":"n.","translation":"河;河流","definition":"a flowing water","root":"riv+-er","family":["rivers"],"examples":["The river is long.","Across the river.","River bank."],"collocations":["across the river","river bank","long river"],"synonyms":["stream"],"antonyms":[],"keyword":"River=瑞沃(谐音)","image":"🏞️","topic":"nature","grade":"chuyi-shang","frequency":3170,"difficulty":1}
,
{"word":"sea","phonetic":"/siː/","pos":"n.","translation":"海;海洋","definition":"a large body of salt water","root":"","family":["seas"],"examples":["The sea is blue.","By the sea.","Sea food."],"collocations":["by the sea","sea food","sea side"],"synonyms":["ocean"],"antonyms":["land"],"keyword":"Sea=西(谐音)","image":"🌊","topic":"nature","grade":"chuyi-shang","frequency":3160,"difficulty":1}
,
{"word":"hand","phonetic":"/hænd/","pos":"n.","translation":"手","definition":"body part at end of arm","root":"","family":["hands","handy"],"examples":["Wash hands.","Give me a hand.","Left hand."],"collocations":["give a hand","hand in","by hand"],"synonyms":["palm"],"antonyms":["foot"],"keyword":"Hand=汉德(谐音)","image":"✋","topic":"body","grade":"chuyi-shang","frequency":3150,"difficulty":1}
,
{"word":"foot","phonetic":"/fʊt/","pos":"n.","translation":"脚;足","definition":"body part at end of leg","root":"","family":["feet"],"examples":["My foot hurts.","On foot.","Foot ball."],"collocations":["on foot","foot ball","at the foot"],"synonyms":[],"antonyms":["hand"],"keyword":"Foot=福特(谐音)","image":"🦶","topic":"body","grade":"chuyi-shang","frequency":3140,"difficulty":1}
,
{"word":"head","phonetic":"/hed/","pos":"n.","translation":"头;头部","definition":"top of body","root":"","family":["heads"],"examples":["Use your head.","Head ache.","Head of class."],"collocations":["head ache","head of","use your head"],"synonyms":["skull"],"antonyms":["foot","tail"],"keyword":"Head=黑的(谐音)","image":"🙂","topic":"body","grade":"chuyi-shang","frequency":3130,"difficulty":1}
,
{"word":"eye","phonetic":"/aɪ/","pos":"n.","translation":"眼睛","definition":"organ of sight","root":"","family":["eyes","eyebrow"],"examples":["Big eyes.","Blue eyes.","Eye ball."],"collocations":["big eyes","eye ball","eye brow"],"synonyms":[],"antonyms":[],"keyword":"Eye=爱(谐音)","image":"👁️","topic":"body","grade":"chuyi-shang","frequency":3120,"difficulty":1}
,
{"word":"ear","phonetic":"/ɪər/","pos":"n.","translation":"耳朵","definition":"organ of hearing","root":"","family":["ears"],"examples":["Big ears.","Ear ring.","Ear ache."],"collocations":["big ears","ear ring","ear ache"],"synonyms":[],"antonyms":[],"keyword":"Ear=伊尔(谐音)","image":"👂","topic":"body","grade":"chuyi-shang","frequency":3110,"difficulty":1}
,
{"word":"nose","phonetic":"/nəʊz/","pos":"n.","translation":"鼻子","definition":"organ of smell","root":"","family":["noses"],"examples":["Big nose.","Nose bleed.","Blow your nose."],"collocations":["big nose","nose bleed","runny nose"],"synonyms":[],"antonyms":[],"keyword":"Nose=诺子(谐音)","image":"👃","topic":"body","grade":"chuyi-shang","frequency":3100,"difficulty":1}
,
{"word":"mouth","phonetic":"/maʊθ/","pos":"n.","translation":"嘴;口","definition":"opening in face","root":"","family":["mouths"],"examples":["Open your mouth.","Big mouth.","Mouth wash."],"collocations":["open mouth","big mouth","by mouth"],"synonyms":[],"antonyms":[],"keyword":"Mouth=矛斯(谐音)","image":"👄","topic":"body","grade":"chuyi-shang","frequency":3090,"difficulty":1}
,
{"word":"face","phonetic":"/feɪs/","pos":"n.","translation":"脸;面孔","definition":"front of head","root":"","family":["faces"],"examples":["Pretty face.","Face to face.","Wash face."],"collocations":["face to face","pretty face","wash face"],"synonyms":["visage"],"antonyms":[],"keyword":"Face=费斯(谐音)","image":"🙂","topic":"body","grade":"chuyi-shang","frequency":3080,"difficulty":1}
,
{"word":"hair","phonetic":"/heər/","pos":"n.","translation":"头发;毛发","definition":"strands growing on head","root":"","family":["hairs","haircut"],"examples":["Long hair.","Black hair.","Hair cut."],"collocations":["long hair","hair cut","wash hair"],"synonyms":[],"antonyms":[],"keyword":"Hair=海尔(谐音)","image":"💇","topic":"body","grade":"chuyi-shang","frequency":3070,"difficulty":1}
,
{"word":"eye","phonetic":"/aɪ/","pos":"n.","translation":"眼睛(同 id189)","definition":"organ of sight","root":"","family":[],"examples":["See with eyes.","Open eyes."],"collocations":[],"synonyms":[],"antonyms":[],"keyword":"重复词,删除","image":"👁️","topic":"body","grade":"chuyi-shang","frequency":3060,"difficulty":1}
,
{"word":"shirt","phonetic":"/ʃɜːrt/","pos":"n.","translation":"衬衫","definition":"a garment for upper body","root":"","family":["shirts"],"examples":["White shirt.","A new shirt.","Shirt and tie."],"collocations":["white shirt","T shirt","shirt collar"],"synonyms":["blouse"],"antonyms":[],"keyword":"Shirt=舍特(谐音)","image":"👕","topic":"clothes","grade":"chuyi-shang","frequency":3050,"difficulty":1}
,
{"word":"shoes","phonetic":"/ʃuːz/","pos":"n.","translation":"鞋","definition":"footwear","root":"","family":["shoe","shoes"],"examples":["A pair of shoes.","New shoes.","Sports shoes."],"collocations":["a pair of shoes","sports shoes","shoe store"],"synonyms":[],"antonyms":[],"keyword":"Shoes=舒子(谐音)","image":"👟","topic":"clothes","grade":"chuyi-shang","frequency":3040,"difficulty":1}
,
{"word":"trousers","phonetic":"/ˈtraʊzərz/","pos":"n.","translation":"裤子","definition":"a garment for legs","root":"trouse+-rs","family":["trouser"],"examples":["Long trousers.","Trousers and shirt.","Brown trousers."],"collocations":["long trousers","trousers and shirt","wear trousers"],"synonyms":["pants"],"antonyms":[],"keyword":"Trousers=超泽斯(谐音)","image":"👖","topic":"clothes","grade":"chuyi-shang","frequency":3030,"difficulty":1}
,
{"word":"dress","phonetic":"/dres/","pos":"n.","translation":"连衣裙","definition":"a garment for women","root":"","family":["dresses"],"examples":["A pretty dress.","Evening dress.","Wedding dress."],"collocations":["pretty dress","evening dress","wedding dress"],"synonyms":["gown"],"antonyms":[],"keyword":"Dress=追斯(谐音)","image":"👗","topic":"clothes","grade":"chuyi-shang","frequency":3020,"difficulty":1}
,
{"word":"hat","phonetic":"/hæt/","pos":"n.","translation":"帽子","definition":"a head covering","root":"","family":["hats"],"examples":["A red hat.","Sun hat.","Hat and coat."],"collocations":["sun hat","hat and coat","wear a hat"],"synonyms":["cap"],"antonyms":[],"keyword":"Hat=哈特(谐音)","image":"🎩","topic":"clothes","grade":"chuyi-shang","frequency":3010,"difficulty":1}
];
